[platformio]
default_envs = esp32-s3-devkitc-1

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags =
    -DFW_VERSION='"0.1.0"'
    ; Console on UART0 / USB-Serial-JTAG, keep the OTG port free for host mode
    -DARDUINO_USB_MODE=1
lib_deps =
    lathoub/AppleMIDI@^3.3.0
    fortyseveneffects/MIDI Library@^5.0.2
