"""Embed web/index.html in the firmware at build time.

The config page is one static file, web/index.html, which fills itself from
the device's JSON endpoints (src/web_ui.cpp). This `pre:` extra_script gzips it
and writes $BUILD_DIR/generated/web_page.h holding the gzipped copy, the plain
copy (for a client that does not accept gzip) and an ETag for each, taken from
the page's content. Nothing generated lands in the source tree.

The gzip header is fixed (mtime 0, OS byte 255 = unknown; Python 3.11+ lets
zlib write the build machine's OS there), so the output depends only on the
page and the zlib build doing the compressing: rebuilding on one machine never
changes it. A different zlib (CI's, say) may pick a different but equally
valid encoding; the ETags hash the plain page, so they match either way. The
header is rewritten only when its content changes, so an unchanged page does
not trigger a rebuild.
"""

import gzip
import hashlib
import os

Import("env")  # noqa: F821  (injected by PlatformIO/SCons)

PAGE = os.path.join(env.subst("$PROJECT_DIR"), "web", "index.html")  # noqa: F821
OUT_DIR = os.path.join(env.subst("$BUILD_DIR"), "generated")  # noqa: F821
OUT = os.path.join(OUT_DIR, "web_page.h")


def c_array(name, data):
    rows = []
    for i in range(0, len(data), 16):
        rows.append("    " + ", ".join("0x%02x" % b for b in data[i:i + 16]) + ",")
    return ("const uint8_t %s[] PROGMEM = {\n%s\n};\nconstexpr size_t %s_LEN = %d;\n"
            % (name, "\n".join(rows), name, len(data)))


raw = open(PAGE, "rb").read()
gz = bytearray(gzip.compress(raw, compresslevel=9, mtime=0))
gz[9] = 255  # OS: unknown, whatever machine built it
gz = bytes(gz)
tag = hashlib.sha256(raw).hexdigest()[:16]

header = (
    "// Generated by tools/embed_web.py from web/index.html. Do not edit.\n"
    "#pragma once\n#include <Arduino.h>\n\n"
    + c_array("WEB_PAGE_GZ", gz) + "\n"
    + c_array("WEB_PAGE_RAW", raw) + "\n"
    + 'constexpr const char* WEB_PAGE_ETAG_GZ = "\\"%s-gz\\"";\n' % tag
    + 'constexpr const char* WEB_PAGE_ETAG_RAW = "\\"%s\\"";\n' % tag
)

os.makedirs(OUT_DIR, exist_ok=True)
old = None
if os.path.exists(OUT):
    with open(OUT, encoding="utf-8") as f:
        old = f.read()
if old != header:
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(header)
    print("embed_web: web/index.html -> %d bytes, %d gzipped" % (len(raw), len(gz)))

env.Append(CPPPATH=[OUT_DIR])  # noqa: F821
